# Generated by Django 2.2.16 on 2020-09-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birthday', models.DateField()),
                ('telephone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Feminino', max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('has_pathology', models.BooleanField(default=False)),
                ('pathology', models.TextField(blank=True, null=True)),
                ('use_medicine', models.BooleanField(default=False)),
                ('medicine', models.TextField(blank=True, null=True)),
                ('has_surgery', models.BooleanField(default=False)),
                ('surgery', models.TextField(blank=True, null=True)),
                ('heart_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('objective', models.CharField(choices=[('Emagrecimento', 'Emagrecimento'), ('Hipertrofia', 'Hipertrofia'), ('Fortalecimento', 'Fortalecimento'), ('Resistência', 'Resistência'), ('Força', 'Força')], default='Emagrecimento', max_length=20)),
                ('has_physical_activity', models.BooleanField(default=False)),
                ('physical_activity', models.TextField(blank=True, null=True)),
                ('sleep_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('has_smoker', models.BooleanField(default=False)),
                ('meals_day', models.IntegerField()),
            ],
        ),
    ]
