# Generated by Django 2.2.16 on 2020-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birthday', models.DateField()),
                ('telephone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=255)),
                ('cpf', models.IntegerField(max_length=11)),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Feminino', max_length=10)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
