# Generated by Django 2.2.16 on 2020-09-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
