# Generated by Django 2.2.16 on 2020-09-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200919_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('has_pathology', models.BooleanField(default=False)),
                ('pathology', models.TextField(null=True)),
                ('use_medicine', models.BooleanField(default=False)),
                ('medicine', models.TextField(null=True)),
                ('has_surgery', models.BooleanField(default=False)),
                ('surgery', models.TextField(null=True)),
                ('heart_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('objective', models.CharField(choices=[('Emagrecimento', 'Emagrecimento'), ('Hipertrofia', 'Hipertrofia'), ('Fortalecimento', 'Fortalecimento'), ('Resistência', 'Resistência'), ('Força', 'Força')], default='Emagrecimento', max_length=10)),
                ('has_physical_activity', models.BooleanField(default=False)),
                ('physical_activity', models.TextField(null=True)),
                ('sleep_hours', models.DecimalField(decimal_places=2, max_digits=2)),
                ('has_smoker', models.BooleanField(default=False)),
                ('meals_day', models.IntegerField()),
            ],
        ),
    ]
