# Generated by Django 2.2.16 on 2020-09-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_anamnese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='heart_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='medicine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='objective',
            field=models.CharField(choices=[('Emagrecimento', 'Emagrecimento'), ('Hipertrofia', 'Hipertrofia'), ('Fortalecimento', 'Fortalecimento'), ('Resistência', 'Resistência'), ('Força', 'Força')], default='Emagrecimento', max_length=20),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='pathology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='physical_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='sleep_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='surgery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
