# Generated by Django 2.2.16 on 2020-09-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(choices=[('Quadríceps', 'Quadríceps'), ('Dorsal', 'Dorsal'), ('Posterior de Coxa', 'Posterior de Coxa'), ('Peitoral', 'Peitoral'), ('Bíceps', 'Bíceps'), ('Tríceps', 'Tríceps'), ('Ombro', 'Ombro'), ('Abdômen', 'Abdômen'), ('Panturrilha', 'Panturrilha'), ('Cardio', 'Cardio')], max_length=20)),
            ],
        ),
    ]
